name: "Libabigail Action"
author: "Vanessa Sochat"
description: "Check for ABI breaks in GitHub actions using libabigail"

inputs:
  abidiff:
    description: "Library inputs required to run abidiff (e.g., should be two libs in order of diff)"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "user-check"
  color: "red"
