name: "Libabigail Action"
author: "Vanessa Sochat"
description: "Check for ABI breaks in GitHub actions using libabigail"

inputs:
  abidiff:
    description: "Library inputs required to run abidiff (e.g., should be two libs in order of diff)"
    required: true
  allow_fail: 
    description: "Allow the ABI check to fail."
    required: true
    default: false
    
outputs:
  retval:
    description: The return value of the action for you to act on   
 
runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "user-check"
  color: "red"
